Tooltip on profile page overhaul (GSI-860)
ghga-de/data-portal-ui pull request #215
Opened 2024-07-05 11:58 UTC by ac-jorellanaf

Changed look of tooltip icon
Info icons now on the right
Added more information for tooltips
Fixed access request mocks ending access before May this year Fixed display issue for dataset access section when dataset could not be matched with an currently valid access request

2024-07-05 12:57 UTC, Cito requested changes

2024-07-05 13:02 UTC, Cito requested changes
The tooltips look much better now, thanks.

2024-07-08 09:46 UTC, ac-jorellanaf commented on src/components/profile/profile.tsx
> +                  address via the data steward must be manually requested.
Done.

2024-07-08 09:46 UTC, ac-jorellanaf commented on src/mocks/data.js
> +    access_starts: "2024-05-12T15:00:00.000Z",
Good idea! Done

2024-07-08 09:46 UTC, ac-jorellanaf commented on src/mocks/data.js
> +    iva_id: "783d9682-d5e5-4ce7-9157-9eeb53a1e9ba",
Done I think

2024-07-08 11:18 UTC, Cito approved these changes
The wide tooltips look better now, but I think making the text left aligned will make them even more readable.

2024-07-08 12:35 UTC, Cito approved these changes

2024-07-08 12:38 UTC, merged