Add OIDC functionality to the frontend (GDEV-1133)
ghga-de/data-portal-ui pull request #93
Opened 2022-08-25 11:04 UTC by Cito

This PR implements the OIDC flow to let users authenticate using LS Login.

A global AuthService object is used as facade for the oidc-client-ts library.

After logging in, the user (for now) is redirected to a simple profile page.

2022-08-26 09:17 UTC, KerstenBreuer approved these changes
Tested on windows and works beautifully.

2022-08-26 11:50 UTC, ac-jorellanaf requested changes
I get this error:

```
The OIDC client ID is missing! index.js:1
    e index.js:1
    AuthService authService.ts:19
    ts authService.ts:141
    ts main.chunk.js:1776
    Webpack 23
        __webpack_require__
        fn
        tsx
        tsx
        __webpack_require__
        fn
        tsx
        tsx
        __webpack_require__
        fn
        tsx
        tsx
        __webpack_require__
        fn
        tsx
        tsx
        __webpack_require__
        fn
        1
        __webpack_require__
        checkDeferredModules
        webpackJsonpCallback
        <anonymous>
```

2022-08-26 11:56 UTC, Cito commented
@Jordy Did you set the client id in the environment? See confluence page "Testing authentication in development".

2022-08-30 14:25 UTC, ac-jorellanaf approved these changes

2022-08-30 14:31 UTC, merged